version: 1.{build}
image: Visual Studio 2019
skip_non_tags: true
clone_folder: C:\projects\hoper
init:
- cmd: git config --global core.autocrlf false
environment:
  PIP: C:\Python38\Scripts\pip.exe
  PYTHON: C:\Python38\python.exe
install:
- cmd: >-
    cd C:\projects\hoper

    C:\Python38\python.exe -m pip install -U pip setuptools pyinstaller

    C:\Python38\python.exe -m pip install -Ur gui.txt
build: off
test_script:
- cmd: >-
    C:\Python38\Scripts\pyinstaller.exe gui.py --log-level CRITICAL -y -F -n hoper_gui.exe

    C:\Python38\Scripts\pyinstaller.exe hoper.py --log-level CRITICAL -y -F -n hoper_cli.exe
artifacts:
- path: dist\hoper_gui.exe
  name: hoper_gui.exe
  type: File
- path: dist\hoper_cli.exe
  name: hoper_cli.exe
  type: File
deploy:
- provider: GitHub
  auth_token:
    secure: Hqebgk6BZ+OiWZTtKwvtUN+HrlbjH1ino7fEKg/VLh13DRBMsGsEWnY2T/EAiPZl
  draft: false
  prerelease: false
  force_update: false
