version: 1.{build}
image: Visual Studio 2019
clone_folder: C:\projects\hoper
init:
- ps: git config --global core.autocrlf false
environment:
  PIP: C:\Python38\Scripts\pip.exe
  PYTHON: C:\Python38\python.exe
install:
- ps: >-
    cd C:\projects\hoper

    python3 -m pip install -U pip setuptools pyinstaller

    python3 -m pip install -Ur gui.txt
build: off
test_script:
- ps: >-
    pyinstaller gui.py --log-level CRITICAL -y -F -n hoper.exe
artifacts:
- path: dist\hoper.exe
  name: hoper.exe
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: Hqebgk6BZ+OiWZTtKwvtUN+HrlbjH1ino7fEKg/VLh13DRBMsGsEWnY2T/EAiPZl
  draft: false
  prerelease: false
  force_update: false
